name: Deploy Storybook to S3
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                    node-version: 18
            - run: npm ci
            - run: npm run build-storybook
            - uses: jakejarvis/s3-sync-action@master
              with:
                args: --delete
              env:
                    AWS_S3_BUCKET: gxt-storybook-deployment 
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    working-directory: ./storybook-static