name: publish on github

on:
  push:
    branches:
      - main

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - run: npm version patch -m "Increment version [skip ci]"
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@gloabal-regulatory-writing-consulting"
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}